name: Regression Tests Blog Agi

on:
  pull_request:    
  workflow_dispatch:   
    inputs:
      browser:
        type: choice
        options:
          - chrome
          - edge
          - firefox
          - electron            
  workflow_call:
    inputs:
        browser:
          required: false
          type: string
          default: "chrome"
     
jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Tests ${{ inputs.browser}}
        if: failure() || success() && github.event_name != 'pull_request'
        run: |
          npm run test:browser ${{ inputs.browser}}

      - name: Run Cypress Tests
        if: (failure() || success()) && github.event_name == 'pull_request'
        run: |
          npm run test:run
          
      - name: Merge Mochawesome Reports
        run: npx mochawesome-merge cypress/reports/*.json > mochawesome.json

      - name: Generate Mochawesome Report
        run: npx marge mochawesome.json -f report -o cypress/reports

      - name: Archive Reports
        uses: actions/upload-artifact@v2
        with:
          name: cypress-reports
          path: cypress/reports/report.html
          
